"""Build a dependency-free, browser-viewable four-page dashboard preview."""
from __future__ import annotations
import json
from pathlib import Path
import pandas as pd

ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/"data"/"processed"; OUT=ROOT/"dashboard"/"interactive_dashboard.html"

def main():
    p=pd.read_csv(DATA/"products.csv"); o=pd.read_csv(DATA/"orders.csv"); u=pd.read_csv(DATA/"users.csv"); a=pd.read_csv(DATA/"ads.csv")
    o=o[o.status.eq("completed")].merge(p[["product_id","category","product_name"]],on="product_id").merge(u[["user_id","region","acquisition_channel"]],on="user_id")
    overview=o.groupby("category").agg(net_sales=("net_sales","sum"),orders=("order_id","nunique"),profit=("net_sales",lambda s:0)).reset_index(); costs=o.groupby("category").cost.sum(); overview["profit"]=overview.net_sales-overview.category.map(costs)
    products=o.groupby(["category","product_name"]).agg(net_sales=("net_sales","sum"),units=("quantity","sum"),profit=("net_sales","sum"),cost=("cost","sum")).reset_index(); products["profit"]=products.profit-products.cost
    users=o.groupby(["region","acquisition_channel"]).agg(users=("user_id","nunique"),net_sales=("net_sales","sum")).reset_index()
    ads=a.groupby(["channel","campaign_name"]).agg(impressions=("impressions","sum"),clicks=("clicks","sum"),spend=("spend","sum"),conversions=("conversions","sum"),revenue=("attributed_revenue","sum")).reset_index(); ads["ctr"]=ads.clicks/ads.impressions; ads["cvr"]=ads.conversions/ads.clicks; ads["roas"]=ads.revenue/ads.spend
    payload={"overview":overview.round(2).to_dict("records"),"products":products.sort_values("net_sales",ascending=False).round(2).to_dict("records"),"users":users.round(2).to_dict("records"),"ads":ads.round(4).to_dict("records")}
    html=TEMPLATE.replace("__DATA__",json.dumps(payload,ensure_ascii=False))
    OUT.write_text(html,encoding="utf-8"); print(OUT)

TEMPLATE='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>E-commerce Operations Analytics</title><style>
:root{--blue:#2563eb;--green:#10b981;--red:#ef4444;--ink:#172033;--muted:#667085;--bg:#f5f7fb}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:Segoe UI,Arial;color:var(--ink)}header{padding:22px 34px;background:#111827;color:#fff;display:flex;justify-content:space-between;align-items:center}header h1{margin:0;font-size:22px}.badge{font-size:12px;background:#334155;padding:7px 11px;border-radius:20px}.wrap{max-width:1320px;margin:22px auto;padding:0 20px}.tabs{display:flex;gap:8px;margin-bottom:16px}.tabs button{border:0;padding:11px 18px;border-radius:9px;background:#e5e7eb;cursor:pointer;font-weight:600}.tabs button.active{background:var(--blue);color:#fff}.page{display:none}.page.active{display:block}.panel{background:#fff;border-radius:16px;padding:22px;box-shadow:0 8px 30px #1f29370d}.top{display:flex;justify-content:space-between;align-items:start}.top h2{margin:0}.sub{color:var(--muted);margin:5px 0 18px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.card{background:#f8fafc;border:1px solid #e7ecf3;border-radius:12px;padding:16px}.card small{color:var(--muted)}.card b{display:block;font-size:24px;margin-top:8px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px}.barrow{display:grid;grid-template-columns:190px 1fr 100px;gap:10px;align-items:center;margin:11px 0}.bar{height:22px;background:linear-gradient(90deg,var(--blue),#60a5fa);border-radius:6px}.insight{background:#eff6ff;border-left:4px solid var(--blue);padding:16px;border-radius:9px;line-height:1.55}select{padding:8px;border:1px solid #cbd5e1;border-radius:8px}footer{color:var(--muted);font-size:12px;margin:18px 2px}@media(max-width:800px){.cards{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.barrow{grid-template-columns:120px 1fr 75px}}
</style></head><body><header><h1>E-commerce Operations Analytics Assistant</h1><span class="badge">Synthetic data · TWD · 2025</span></header><div class="wrap"><div class="tabs"><button class="active" data-page="overview">01 Overview</button><button data-page="products">02 Products</button><button data-page="users">03 Customers</button><button data-page="ads">04 Advertising</button></div>
<section id="overview" class="page active"><div class="panel"><div class="top"><div><h2>Operations overview</h2><p class="sub">Where do sales and profit come from?</p></div><select id="cat"><option>All categories</option></select></div><div class="cards" id="overviewCards"></div><div class="grid"><div id="overviewBars"></div><div class="insight"><b>Decision path</b><p>Use category mix to find growth, then verify profit before scaling. Filters update the KPI cards and ranking.</p></div></div></div></section>
<section id="products" class="page"><div class="panel"><div class="top"><div><h2>Product analysis</h2><p class="sub">Which products combine demand and contribution?</p></div><select id="productCategory"><option>All categories</option></select></div><div class="cards" id="productCards"></div><div class="grid"><div id="productBars"></div><div class="insight"><b>Action</b><p>Protect top contributors, review high-volume low-profit items, and treat Opportunity Score as a research shortlist.</p></div></div></div></section>
<section id="users" class="page"><div class="panel"><div class="top"><div><h2>Customer analysis</h2><p class="sub">Which regions and acquisition channels create value?</p></div><select id="userRegion"><option>All regions</option></select></div><div class="cards" id="userCards"></div><div class="grid"><div id="userBars"></div><div class="insight"><b>Action</b><p>Pair channel quality with RFM lifecycle treatment; avoid judging acquisition on first-order volume alone.</p></div></div></div></section>
<section id="ads" class="page"><div class="panel"><div class="top"><div><h2>Advertising analysis</h2><p class="sub">Where should the next TWD of spend go?</p></div><select id="channel"><option>All channels</option></select></div><div class="cards" id="adCards"></div><div class="grid"><div id="adBars"></div><div class="insight"><b>Action</b><p>Scale high-ROAS campaigns gradually and diagnose CTR versus CVR before reallocating budget.</p></div></div></div></section><footer>Portfolio preview. All data is synthetic; no real Shopee performance is implied.</footer></div>
<script>const D=__DATA__;const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(Number.isFinite(n)?n:0),money=n=>'NT$ '+fmt(n),ratio=(n,d)=>d?n/d:0;function cards(id,items){document.getElementById(id).innerHTML=items.map(x=>`<div class="card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}function bars(id,rows,label,key,suffix=''){let m=Math.max(...rows.map(r=>r[key]),1);document.getElementById(id).innerHTML=rows.slice(0,7).map(r=>`<div class="barrow"><span>${r[label]}</span><div class="bar" style="width:${Math.max(2,100*r[key]/m)}%"></div><b>${fmt(r[key])}${suffix}</b></div>`).join('')}
function renderOverview(){let v=document.getElementById('cat').value,r=v==='All categories'?D.overview:D.overview.filter(x=>x.category===v),sales=r.reduce((s,x)=>s+x.net_sales,0),orders=r.reduce((s,x)=>s+x.orders,0),profit=r.reduce((s,x)=>s+x.profit,0);cards('overviewCards',[['Net sales',money(sales)],['Orders',fmt(orders)],['Gross profit',money(profit)],['Margin',((profit/sales||0)*100).toFixed(1)+'%']]);bars('overviewBars',r.sort((a,b)=>b.net_sales-a.net_sales),'category','net_sales')}
function renderAds(){let v=document.getElementById('channel').value,r=v==='All channels'?D.ads:D.ads.filter(x=>x.channel===v),sp=r.reduce((s,x)=>s+x.spend,0),rev=r.reduce((s,x)=>s+x.revenue,0),clk=r.reduce((s,x)=>s+x.clicks,0),imp=r.reduce((s,x)=>s+x.impressions,0),conv=r.reduce((s,x)=>s+x.conversions,0);cards('adCards',[['Spend',money(sp)],['CTR',(100*ratio(clk,imp)).toFixed(2)+'%'],['CVR',(100*ratio(conv,clk)).toFixed(2)+'%'],['ROAS',ratio(rev,sp).toFixed(2)+'x']]);bars('adBars',r.sort((a,b)=>b.roas-a.roas),'campaign_name','roas','x')}
function renderProducts(){let v=document.getElementById('productCategory').value,r=v==='All categories'?D.products:D.products.filter(x=>x.category===v),top=r.slice().sort((a,b)=>b.net_sales-a.net_sales).slice(0,20);cards('productCards',[['Products',fmt(r.length)],['Net sales',money(r.reduce((s,x)=>s+x.net_sales,0))],['Units',fmt(r.reduce((s,x)=>s+x.units,0))],['Gross profit',money(r.reduce((s,x)=>s+x.profit,0))]]);bars('productBars',top,'product_name','net_sales')}
function renderUsers(){let v=document.getElementById('userRegion').value,r=v==='All regions'?D.users:D.users.filter(x=>x.region===v),sales=r.reduce((s,x)=>s+x.net_sales,0),buyers=r.reduce((s,x)=>s+x.users,0);cards('userCards',[['Regions',fmt(new Set(r.map(x=>x.region)).size)],['Channels',fmt(new Set(r.map(x=>x.acquisition_channel)).size)],['Buyers',fmt(buyers)],['Net sales',money(sales)]]);bars('userBars',r.slice().sort((a,b)=>b.net_sales-a.net_sales),'acquisition_channel','net_sales')}
const catSelect=document.getElementById('cat'),productSelect=document.getElementById('productCategory'),regionSelect=document.getElementById('userRegion'),channelSelect=document.getElementById('channel');document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active')});[...new Set(D.overview.map(x=>x.category))].forEach(x=>{catSelect.add(new Option(x,x));productSelect.add(new Option(x,x))});[...new Set(D.users.map(x=>x.region))].forEach(x=>regionSelect.add(new Option(x,x)));[...new Set(D.ads.map(x=>x.channel))].forEach(x=>channelSelect.add(new Option(x,x)));catSelect.onchange=renderOverview;productSelect.onchange=renderProducts;regionSelect.onchange=renderUsers;channelSelect.onchange=renderAds;renderOverview();renderProducts();renderUsers();renderAds();</script></body></html>'''
if __name__=="__main__":main()
