/// Dedicated continuous date dimension for 2025 reporting.
table calendar
	lineageTag: 7fc24490-b86b-4eee-8e4b-d27ace14d532
	dataCategory: Time

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 7beb564b-cd97-474a-8408-2b29c81b5c40
		summarizeBy: none
		sourceColumn: date

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: 519f6707-f366-408f-8e09-0a56fb3cdab9
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		lineageTag: b435867e-b67d-41e8-91c5-9df44db836c4
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: string
		lineageTag: 2f89328d-e87e-41bb-a0a0-ddb9dbc108e1
		summarizeBy: none
		sourceColumn: month
		sortByColumn: month_sort

	column month_sort
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a394e074-b172-4348-866c-11f56a8d28d3
		summarizeBy: none
		sourceColumn: month_sort

	column week
		dataType: int64
		formatString: 0
		lineageTag: be7641eb-ab41-4a02-b39c-4fcef16089d0
		summarizeBy: none
		sourceColumn: week

	column weekday
		dataType: string
		lineageTag: e2e3346b-0167-401f-b107-e13367b7919f
		summarizeBy: none
		sourceColumn: weekday

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: aba3b8cd-d1dc-4571-8056-4f64bd6cf6e3
		summarizeBy: none
		sourceColumn: is_weekend

	column is_promotion
		dataType: int64
		formatString: 0
		lineageTag: fc8eb8a8-d0cf-41e1-a59c-6b088c42b126
		summarizeBy: none
		sourceColumn: is_promotion

	hierarchy 'Date Hierarchy'
		lineageTag: b3848ca1-5b73-4c19-a4b3-acf0c45b317d

		level Year
			lineageTag: 27b1d3b4-e99b-449b-99cc-e5431f1587c9
			column: year

		level Quarter
			lineageTag: f8d7611f-3ed4-4ee9-8d32-2113934e3004
			column: quarter

		level Month
			lineageTag: 04d2074c-47d3-465a-872d-000df78c97c0
			column: month

		level Date
			lineageTag: b15f2711-32d3-4519-b8c6-3a7a65287176
			column: date

	partition calendar = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\calendar.csv"), [Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month", type text}, {"week", Int64.Type}, {"weekday", type text}, {"is_weekend", Int64.Type}, {"is_promotion", Int64.Type}}, "en-US"),
				    #"Added Month Sort" = Table.AddColumn(#"Changed Type", "month_sort", each [year] * 100 + Date.Month([date]), Int64.Type)
				in
				    #"Added Month Sort"
