/// Auditable English metric names, formulas, grains, scopes and source fields for the Olist analytics layer.
table olist_metric_definitions
	lineageTag: 1e401cba-cf8f-9e1a-13a4-56c877c04b70

	column metric_name
		dataType: string
		lineageTag: 7ef6fe07-9047-7bb4-ffa6-2ade44eb0ae2
		summarizeBy: none
		sourceColumn: metric_name

	column display_name
		dataType: string
		lineageTag: ff58aa37-a813-3fb8-9df0-583163752c9b
		summarizeBy: none
		sourceColumn: display_name

	column definition
		dataType: string
		lineageTag: 71cb0e29-37bf-13d4-27cf-5c1d56b30ba0
		summarizeBy: none
		sourceColumn: definition

	column formula
		dataType: string
		lineageTag: 84285dda-6040-ca29-c4ca-b94ac972ac09
		summarizeBy: none
		sourceColumn: formula

	column order_scope
		dataType: string
		lineageTag: c4324298-b01b-b3d3-3625-b6005e971346
		summarizeBy: none
		sourceColumn: order_scope

	column grain
		dataType: string
		lineageTag: 9ccd5a52-3099-edf0-b600-c7c5ef55ac81
		summarizeBy: none
		sourceColumn: grain

	column source_fields
		dataType: string
		lineageTag: 8dcca92a-32d1-60bb-80be-459577e4911a
		summarizeBy: none
		sourceColumn: source_fields

	column currency_code
		dataType: string
		lineageTag: 80242978-8fec-4119-95e6-efa9b33a52fa
		summarizeBy: none
		sourceColumn: currency_code

	column _analytics_build_id
		dataType: string
		isHidden
		lineageTag: 68b965c5-904f-17fd-00ff-1d361b4bd569
		summarizeBy: none
		sourceColumn: _analytics_build_id

	column _built_at
		dataType: string
		isHidden
		lineageTag: 3ac2580f-0a76-55a8-93c6-f8b04ffc94d4
		summarizeBy: none
		sourceColumn: _built_at

	partition olist_metric_definitions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\olist_metric_definitions.csv"), [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"metric_name", type text}, {"display_name", type text}, {"definition", type text}, {"formula", type text}, {"order_scope", type text}, {"grain", type text}, {"source_fields", type text}, {"currency_code", type text}, {"_analytics_build_id", type text}, {"_built_at", type text}}, "en-US")
				in
				    #"Changed Type"
